
Please fill out:
* Student name: **Justin Mawira, Clive Kinyanjui, Brian Ireri, Faith John, Sharahbil Abdi (Group 3)**
* Student pace: **full time**
* Scheduled project review date/time: 
* Instructor name: **Mwikali**
* Blog post URL:

## Project Overview
Your company has decided to create a new movie studio, but they don’t know anything about creating movies. You are charged with exploring what types of films are currently doing the best at the box office. You must then translate those findings into actionable insights that the head of your company's new movie studio can use to help decide what type of films to create.

In [47]:
import pandas as pd
import sqlite3

In [48]:
# make a connection
conn = sqlite3.connect('../Data/im.db')

# create a cursor object
cur = conn.cursor()

In [49]:
pd.read_sql("""
SELECT name AS Table_Names
FROM sqlite_master
WHERE type = 'table'
""", conn)

     Table_Names
0   movie_basics
1      directors
2      known_for
3     movie_akas
4  movie_ratings
5        persons
6     principals
7        writers

* _The tables from the imdb dataset do not have revenue data_

* _The only imdb metric for 'doing the best at the box office' is ratings_

In [50]:
pd.read_sql("""
SELECT *
FROM movie_basics
""", conn)

,movie_id,primary_title,original_title,start_year,runtime_minutes,genres
0,tt0063540,Sunghursh,Sunghursh,2013,175.0,"Action,Crime,Drama"
1,tt0066787,One Day Before the Rainy Season,Ashad Ka Ek Din,2019,114.0,"Biography,Drama"
2,tt0069049,The Other Side of the Wind,The Other Side of the Wind,2018,122.0,Drama
3,tt0069204,Sabse Bada Sukh,Sabse Bada Sukh,2018,NaN,"Comedy,Drama"
4,tt0100275,The Wandering Soap Opera,La Telenovela Errante,2017,80.0,"Comedy,Drama,Fantasy"
...,...,...,...,...,...,...
146139,tt9916538,Kuambil Lagi Hatiku,Kuambil Lagi Hatiku,2019,123.0,Drama
146140,tt9916622,Rodolpho Teóphilo - O Legado de um Pioneiro,Rodolpho Teóphilo - O Legado de um Pioneiro,2015,NaN,Documentary
146141,tt9916706,Dankyavar Danka,Dankyavar Danka,2013,NaN,Comedy
146142,tt9916730,6 Gunn,6 Gunn,2017,116.0,None
146143,tt9916754,Chico Albuquerque - Revelações,Chico Albuquerque - Revelações,2013,NaN,Documentary

In [65]:
pd.read_sql("""
SELECT *
FROM movie_basics
JOIN movie_ratings USING (movie_id)
GROUP BY movie_basics.movie_id, movie_basics.primary_title
ORDER BY averagerating DESC;
""", conn)

,movie_id,primary_title,original_title,start_year,runtime_minutes,genres,averagerating,numvotes
0,tt10176328,Exteriores: Mulheres Brasileiras na Diplomacia,Exteriores: Mulheres Brasileiras na Diplomacia,2018,52.0,Documentary,10.0,5
1,tt10378660,The Dark Knight: The Ballad of the N Word,The Dark Knight: The Ballad of the N Word,2018,129.0,"Comedy,Drama",10.0,5
2,tt1770682,Freeing Bernie Baran,Freeing Bernie Baran,2010,100.0,"Crime,Documentary",10.0,5
3,tt2632430,Hercule contre Hermès,Hercule contre Hermès,2012,72.0,Documentary,10.0,5
4,tt4109192,I Was Born Yesterday!,I Was Born Yesterday!,2015,31.0,Documentary,10.0,6
...,...,...,...,...,...,...,...,...
73851,tt8446392,La Scelta Impossibile,La Scelta Impossibile,2018,64.0,Drama,1.0,5
73852,tt8654080,Overdose of Gore: Crime born Crime,Overdose of Gore: Crime born Crime,2015,46.0,Horror,1.0,21
73853,tt9005484,Roofied: The Lethal Dose,Roofied: The Lethal Dose,2019,NaN,Drama,1.0,112
73854,tt9352262,The Defender,The Defender,2018,88.0,Drama,1.0,16
73855,tt9378134,Startup Girls,Startup Girls,2018,94.0,"Comedy,Drama",1.0,18

In [52]:
pd.read_sql("""
SELECT *
FROM movie_ratings
WHERE movie_id = 'tt0451279'
""", conn)

    movie_id  averagerating  numvotes
0  tt0451279            7.5    487527

In [53]:
pd.read_sql("""
SELECT *
FROM movie_ratings
WHERE movie_id = 'tt0369610'
""", conn)

    movie_id  averagerating  numvotes
0  tt0369610            7.0    539338

In [66]:
budget_numbers_df = pd.read_csv("../Data/tn.movie_budgets.csv.gz")
budget_numbers_df

,id,release_date,movie,production_budget,domestic_gross,worldwide_gross
0,1,"Dec 18, 2009",Avatar,"$425,000,000","$760,507,625","$2,776,345,279"
1,2,"May 20, 2011",Pirates of the Caribbean: On Stranger Tides,"$410,600,000","$241,063,875","$1,045,663,875"
2,3,"Jun 7, 2019",Dark Phoenix,"$350,000,000","$42,762,350","$149,762,350"
3,4,"May 1, 2015",Avengers: Age of Ultron,"$330,600,000","$459,005,868","$1,403,013,963"
4,5,"Dec 15, 2017",Star Wars Ep. VIII: The Last Jedi,"$317,000,000","$620,181,382","$1,316,721,747"
...,...,...,...,...,...,...
5777,78,"Dec 31, 2018",Red 11,"$7,000",$0,$0
5778,79,"Apr 2, 1999",Following,"$6,000","$48,482","$240,495"
5779,80,"Jul 13, 2005",Return to the Land of Wonders,"$5,000","$1,338","$1,338"
5780,81,"Sep 29, 2015",A Plague So Pleasant,"$1,400",$0,$0
5781,82,"Aug 5, 2005",My Date With Drew,"$1,100","$181,041","$181,041"

In [55]:
budget_numbers_df.dtypes

id                    int64
release_date         object
movie                object
production_budget    object
domestic_gross       object
worldwide_gross      object
dtype: object

In [56]:
budget_numbers_df.isnull().sum()

id                   0
release_date         0
movie                0
production_budget    0
domestic_gross       0
worldwide_gross      0
dtype: int64

In [67]:
budget_numbers_df_copy = budget_numbers_df.copy()

# Clean & convert columns to numeric
budget_numbers_df_copy['production_budget'] = (
    budget_numbers_df_copy['production_budget']
    .str.replace('$', '', regex=False)  # remove dollar sign
    .str.replace(',', '', regex=False)  # remove commas
    .astype(float)                       # convert to float
)

budget_numbers_df_copy['domestic_gross'] = (
    budget_numbers_df_copy['domestic_gross']
    .str.replace('$', '', regex=False)
    .str.replace(',', '', regex=False)
    .astype(float)
)

budget_numbers_df_copy['worldwide_gross'] = (
    budget_numbers_df_copy['worldwide_gross']
    .str.replace('$', '', regex=False)
    .str.replace(',', '', regex=False)
    .astype(float)
)

# Calculate net gross
budget_numbers_df_copy['net_profit'] = budget_numbers_df_copy['worldwide_gross'] - budget_numbers_df_copy['production_budget']

# Calculate ROI
budget_numbers_df_copy['ROI'] = budget_numbers_df_copy['net_profit'] / budget_numbers_df_copy['production_budget']

In [68]:
budget_numbers_df_copy

,id,release_date,movie,production_budget,domestic_gross,worldwide_gross,net_profit,ROI
0,1,"Dec 18, 2009",Avatar,425000000.0,760507625.0,2.776345e+09,2.351345e+09,5.532577
1,2,"May 20, 2011",Pirates of the Caribbean: On Stranger Tides,410600000.0,241063875.0,1.045664e+09,6.350639e+08,1.546673
2,3,"Jun 7, 2019",Dark Phoenix,350000000.0,42762350.0,1.497624e+08,-2.002376e+08,-0.572108
3,4,"May 1, 2015",Avengers: Age of Ultron,330600000.0,459005868.0,1.403014e+09,1.072414e+09,3.243841
4,5,"Dec 15, 2017",Star Wars Ep. VIII: The Last Jedi,317000000.0,620181382.0,1.316722e+09,9.997217e+08,3.153696
...,...,...,...,...,...,...,...,...
5777,78,"Dec 31, 2018",Red 11,7000.0,0.0,0.000000e+00,-7.000000e+03,-1.000000
5778,79,"Apr 2, 1999",Following,6000.0,48482.0,2.404950e+05,2.344950e+05,39.082500
5779,80,"Jul 13, 2005",Return to the Land of Wonders,5000.0,1338.0,1.338000e+03,-3.662000e+03,-0.732400
5780,81,"Sep 29, 2015",A Plague So Pleasant,1400.0,0.0,0.000000e+00,-1.400000e+03,-1.000000
5781,82,"Aug 5, 2005",My Date With Drew,1100.0,181041.0,1.810410e+05,1.799410e+05,163.582727

In [69]:
budget_numbers_df_copy.sort_values('net_profit', ascending=False).head(20)

,id,release_date,movie,production_budget,domestic_gross,worldwide_gross,net_profit,ROI
0,1,"Dec 18, 2009",Avatar,425000000.0,760507625.0,2.776345e+09,2.351345e+09,5.532577
42,43,"Dec 19, 1997",Titanic,200000000.0,659363944.0,2.208208e+09,2.008208e+09,10.041042
6,7,"Apr 27, 2018",Avengers: Infinity War,300000000.0,678815482.0,2.048134e+09,1.748134e+09,5.827114
5,6,"Dec 18, 2015",Star Wars Ep. VII: The Force Awakens,306000000.0,936662225.0,2.053311e+09,1.747311e+09,5.710167
33,34,"Jun 12, 2015",Jurassic World,215000000.0,652270625.0,1.648855e+09,1.433855e+09,6.669092
66,67,"Apr 3, 2015",Furious 7,190000000.0,353007020.0,1.518723e+09,1.328723e+09,6.993278
26,27,"May 4, 2012",The Avengers,225000000.0,623279547.0,1.517936e+09,1.292936e+09,5.746382
260,61,"Jul 15, 2011",Harry Potter and the Deathly Hallows: Part II,125000000.0,381193157.0,1.341693e+09,1.216693e+09,9.733545
41,42,"Feb 16, 2018",Black Panther,200000000.0,700059566.0,1.348258e+09,1.148258e+09,5.741291
112,13,"Jun 22, 2018",Jurassic World: Fallen Kingdom,170000000.0,417719760.0,1.305773e+09,1.135773e+09,6.681016
155,56,"Nov 22, 2013",Frozen,150000000.0,400738009.0,1.272470e+09,1.122470e+09,7.483133
134,35,"Mar 17, 2017",Beauty and the Beast,160000000.0,504014165.0,1.259200e+09,1.099200e+09,6.869998
672,73,"Jul 10, 2015",Minions,74000000.0,336045770.0,1.160336e+09,1.086336e+09,14.680219
3,4,"May 1, 2015",Avengers: Age of Ultron,330600000.0,459005868.0,1.403014e+09,1.072414e+09,3.243841
425,26,"Dec 17, 2003",The Lord of the Rings: The Return of the King,94000000.0,377845905.0,1.141403e+09,1.047403e+09,11.142589
43,44,"Jun 15, 2018",Incredibles 2,200000000.0,608581744.0,1.242521e+09,1.042521e+09,5.212604
47,48,"May 3, 2013",Iron Man 3,200000000.0,408992272.0,1.215392e+09,1.015392e+09,5.076961
4,5,"Dec 15, 2017",Star Wars Ep. VIII: The Last Jedi,317000000.0,620181382.0,1.316722e+09,9.997217e+08,3.153696
135,36,"Dec 21, 2018",Aquaman,160000000.0,335061807.0,1.146895e+09,9.868946e+08,6.168092
22,23,"Apr 14, 2017",The Fate of the Furious,250000000.0,225764765.0,1.234846e+09,9.848463e+08,3.939385

In [72]:
budget_numbers_df_copy.sort_values('net_profit', ascending=True).head(20)

,id,release_date,movie,production_budget,domestic_gross,worldwide_gross,net_profit,ROI
2,3,"Jun 7, 2019",Dark Phoenix,350000000.0,42762350.0,149762350.0,-200237650.0,-0.572108
194,95,"Dec 31, 2020",Moonfall,150000000.0,0.0,0.0,-150000000.0,-1.000000
193,94,"Mar 11, 2011",Mars Needs Moms,150000000.0,21392758.0,39549758.0,-110450242.0,-0.736335
341,42,"Jun 14, 2019",Men in Black: International,110000000.0,3100000.0,3100000.0,-106900000.0,-0.971818
352,53,"Apr 27, 2001",Town & Country,105000000.0,6712451.0,10364769.0,-94635231.0,-0.901288
404,5,"Aug 16, 2002",The Adventures of Pluto Nash,100000000.0,4411102.0,7094995.0,-92905005.0,-0.929050
479,80,"Dec 13, 2017",Bright,90000000.0,0.0,0.0,-90000000.0,-1.000000
480,81,"Dec 31, 2019",Army of the Dead,90000000.0,0.0,0.0,-90000000.0,-1.000000
535,36,"Feb 21, 2020",Call of the Wild,82000000.0,0.0,0.0,-82000000.0,-1.000000
477,78,"Apr 21, 2017",The Promise,90000000.0,8224288.0,10551417.0,-79448583.0,-0.882762
619,20,"Jan 22, 2019",Renegades,77500000.0,0.0,1521672.0,-75978328.0,-0.980366
671,72,"Dec 31, 2019",355,75000000.0,0.0,0.0,-75000000.0,-1.000000
670,71,"Aug 30, 2019",PLAYMOBIL,75000000.0,0.0,0.0,-75000000.0,-1.000000
607,8,"Sep 2, 2005",A Sound of Thunder,80000000.0,1900451.0,6300451.0,-73699549.0,-0.921244
435,36,"Dec 22, 1995",Cutthroat Island,92000000.0,10017322.0,18517322.0,-73482678.0,-0.798725
300,1,"Dec 17, 2010",How Do You Know?,120000000.0,30212620.0,49628177.0,-70371823.0,-0.586432
669,70,"Feb 23, 2001",Monkeybone,75000000.0,5409517.0,5409517.0,-69590483.0,-0.927873
478,79,"Nov 24, 2010",The Nutcracker in 3D,90000000.0,195459.0,20466016.0,-69533984.0,-0.772600
434,35,"Apr 9, 2004",The Alamo,92000000.0,22406362.0,23911362.0,-68088638.0,-0.740094
820,21,"Oct 26, 2018",Air Strike,65000000.0,0.0,516279.0,-64483721.0,-0.992057

In [73]:
budget_numbers_df_copy.sort_values('ROI', ascending=False).head(30)

,id,release_date,movie,production_budget,domestic_gross,worldwide_gross,net_profit,ROI
5745,46,"Jun 30, 1972",Deep Throat,25000.0,45000000.0,45000000.0,44975000.0,1799.000000
5613,14,"Mar 21, 1980",Mad Max,200000.0,8750000.0,99750000.0,99550000.0,497.750000
5492,93,"Sep 25, 2009",Paranormal Activity,450000.0,107918810.0,194183034.0,193733034.0,430.517853
5679,80,"Jul 10, 2015",The Gallows,100000.0,22764410.0,41656474.0,41556474.0,415.564740
5406,7,"Jul 14, 1999",The Blair Witch Project,600000.0,140539099.0,248300000.0,247700000.0,412.833333
5709,10,"May 7, 2004",Super Size Me,65000.0,11529368.0,22233808.0,22168808.0,341.058585
5346,47,"Aug 13, 1942",Bambi,858000.0,102797000.0,268000000.0,267142000.0,311.354312
5773,74,"Feb 26, 1993",El Mariachi,7000.0,2040920.0,2041928.0,2034928.0,290.704000
5676,77,"Oct 1, 1968",Night of the Living Dead,114000.0,12087064.0,30087064.0,29973064.0,262.921614
5210,11,"Nov 21, 1976",Rocky,1000000.0,117235147.0,225000000.0,224000000.0,224.000000
5536,37,"Oct 17, 1978",Halloween,325000.0,47000000.0,70000000.0,69675000.0,214.384615
5715,16,"Aug 9, 1995",The Brothers McMullen,50000.0,10426506.0,10426506.0,10376506.0,207.530120
5665,66,"Oct 18, 1974",The Texas Chainsaw Massacre,140000.0,26572439.0,26572439.0,26432439.0,188.803136
5372,73,"Aug 11, 1973",American Graffiti,777000.0,115000000.0,140000000.0,139223000.0,179.180180
5781,82,"Aug 5, 2005",My Date With Drew,1100.0,181041.0,181041.0,179941.0,163.582727
5656,57,"May 16, 2007",Once,150000.0,9445857.0,23323631.0,23173631.0,154.490873
5742,43,"Oct 19, 1994",Clerks,27000.0,3073428.0,3894240.0,3867240.0,143.231111
5612,13,"Jul 25, 1969",The Stewardesses,200000.0,13500000.0,25000000.0,24800000.0,124.000000
5117,18,"Dec 21, 1937",Snow White and the Seven Dwarfs,1488000.0,184925486.0,184925486.0,183437486.0,123.277880
5357,58,"Jan 1, 1971",Billy Jack,800000.0,98000000.0,98000000.0,97200000.0,121.500000
5774,75,"Oct 8, 2004",Primer,7000.0,424760.0,841926.0,834926.0,119.275143
5746,47,"Aug 1, 1997",In the Company of Men,25000.0,2883661.0,2883661.0,2858661.0,114.346440
5507,8,"Jun 11, 2004",Napoleon Dynamite,400000.0,44540956.0,46122713.0,45722713.0,114.306782
5430,31,"Aug 6, 2004",Open Water,500000.0,30500882.0,55518641.0,55018641.0,110.037282
5424,25,"May 9, 1980",Friday the 13th,550000.0,39754601.0,59754601.0,59204601.0,107.644729
5680,81,"Sep 29, 2006",Facing the Giants,100000.0,10178331.0,10243159.0,10143159.0,101.431590
5211,12,"Jan 6, 2012",The Devil Inside,1000000.0,53262945.0,101759490.0,100759490.0,100.759490
5655,56,"Jan 1, 1971",Sweet Sweetback's Baad Asssss Song,150000.0,15200000.0,15200000.0,15050000.0,100.333333
4567,68,"Dec 15, 1939",Gone with the Wind,3900000.0,198680470.0,390525192.0,386625192.0,99.134665
5677,78,"Feb 8, 1915",The Birth of a Nation,110000.0,10000000.0,11000000.0,10890000.0,99.000000

## Total (Worldwide) Gross
the money a movie made worldwide, ie domestic + international

## Net Profit (or Loss)
production budget subtracted from the money a movie made worldwide, ie. 
the total amount of money lost or gained

## Return on Investment
financial ratio that measures the profitability of an investment by by comparing its gain or loss relative to its cost

represents efficiency; a movie can have the greatest ROI but not necessarily the most profit

eg. returning a profit of $1000 from an investment of $10

* _17 out of 20 made profits >$1,000,000,000_

* _6 of the 20 most profitable films were superhero movies_

* _28 movies had an ROI > 100; none of them superhero movies & most with a production budget <$1,000,000_

In [60]:
boxoffice_df = pd.read_csv("../Data/bom.movie_gross.csv.gz")

In [61]:
boxoffice_df.isnull().sum()

title                0
studio               5
domestic_gross      28
foreign_gross     1350
year                 0
dtype: int64

In [62]:
boxoffice_df.dtypes

title              object
studio             object
domestic_gross    float64
foreign_gross      object
year                int64
dtype: object

In [74]:
boxoffice_df

,title,studio,domestic_gross,foreign_gross,year
0,Toy Story 3,BV,415000000.0,652000000,2010
1,Alice in Wonderland (2010),BV,334200000.0,691300000,2010
2,Harry Potter and the Deathly Hallows Part 1,WB,296000000.0,664300000,2010
3,Inception,WB,292600000.0,535700000,2010
4,Shrek Forever After,P/DW,238700000.0,513900000,2010
...,...,...,...,...,...
3382,The Quake,Magn.,6200.0,NaN,2018
3383,Edward II (2018 re-release),FM,4800.0,NaN,2018
3384,El Pacto,Sony,2500.0,NaN,2018
3385,The Swan,Synergetic,2400.0,NaN,2018
3386,An Actor Prepares,Grav.,1700.0,NaN,2018

In [63]:
boxoffice_df_copy = boxoffice_df.copy()

# Convert column to numeric
boxoffice_df_copy['foreign_gross'] = pd.to_numeric(boxoffice_df_copy['foreign_gross'], errors='coerce')

# Calculate total gross
boxoffice_df_copy['total_gross'] = boxoffice_df_copy['domestic_gross'] + boxoffice_df_copy['foreign_gross']

In [64]:
boxoffice_df_copy.sort_values('total_gross', ascending=False).head(20)

,title,studio,domestic_gross,foreign_gross,year,total_gross
727,Marvel's The Avengers,BV,623400000.0,895500000.0,2012,1.518900e+09
1875,Avengers: Age of Ultron,BV,459000000.0,946400000.0,2015,1.405400e+09
3080,Black Panther,BV,700100000.0,646900000.0,2018,1.347000e+09
328,Harry Potter and the Deathly Hallows Part 2,WB,381000000.0,960500000.0,2011,1.341500e+09
2758,Star Wars: The Last Jedi,BV,620200000.0,712400000.0,2017,1.332600e+09
3081,Jurassic World: Fallen Kingdom,Uni.,417700000.0,891800000.0,2018,1.309500e+09
1127,Frozen,BV,400700000.0,875700000.0,2013,1.276400e+09
2759,Beauty and the Beast (2017),BV,504000000.0,759500000.0,2017,1.263500e+09
3082,Incredibles 2,BV,608600000.0,634200000.0,2018,1.242800e+09
1128,Iron Man 3,BV,409000000.0,805800000.0,2013,1.214800e+09
1876,Minions,Uni.,336000000.0,823400000.0,2015,1.159400e+09
2322,Captain America: Civil War,BV,408100000.0,745200000.0,2016,1.153300e+09
3083,Aquaman,WB,335100000.0,812700000.0,2018,1.147800e+09
329,Transformers: Dark of the Moon,P/DW,352400000.0,771400000.0,2011,1.123800e+09
728,Skyfall,Sony,304400000.0,804200000.0,2012,1.108600e+09
1477,Transformers: Age of Extinction,Par.,245400000.0,858600000.0,2014,1.104000e+09
729,The Dark Knight Rises,WB,448100000.0,636800000.0,2012,1.084900e+09
0,Toy Story 3,BV,415000000.0,652000000.0,2010,1.067000e+09
2323,Rogue One: A Star Wars Story,BV,532200000.0,523900000.0,2016,1.056100e+09
330,Pirates of the Caribbean: On Stranger Tides,BV,241100000.0,804600000.0,2011,1.045700e+09

* The top 3 highest-grossing films (total gross) are all superhero movies

* 7 of the top 20 are superhero movies

* 4 of the 20 are animated movies

* 12 of the top 20 films are from the same studio - BV

* The box office database doesn't reveal how profitable each movie was

In [81]:
pd.read_csv(
    '../Data/rt.reviews.tsv.gz',
    sep='\t',
    encoding='latin-1'
)

,id,review,rating,fresh,critic,top_critic,publisher,date
0,3,A distinctly gallows take on contemporary fina...,3/5,fresh,PJ Nabarro,0,Patrick Nabarro,"November 10, 2018"
1,3,It's an allegory in search of a meaning that n...,NaN,rotten,Annalee Newitz,0,io9.com,"May 23, 2018"
2,3,... life lived in a bubble in financial dealin...,NaN,fresh,Sean Axmaker,0,Stream on Demand,"January 4, 2018"
3,3,Continuing along a line introduced in last yea...,NaN,fresh,Daniel Kasman,0,MUBI,"November 16, 2017"
4,3,... a perverse twist on neorealism...,NaN,fresh,NaN,0,Cinema Scope,"October 12, 2017"
...,...,...,...,...,...,...,...,...
54427,2000,The real charm of this trifle is the deadpan c...,NaN,fresh,Laura Sinagra,1,Village Voice,"September 24, 2002"
54428,2000,NaN,1/5,rotten,Michael Szymanski,0,Zap2it.com,"September 21, 2005"
54429,2000,NaN,2/5,rotten,Emanuel Levy,0,EmanuelLevy.Com,"July 17, 2005"
54430,2000,NaN,2.5/5,rotten,Christopher Null,0,Filmcritic.com,"September 7, 2003"
54431,2000,NaN,3/5,fresh,Nicolas Lacroix,0,Showbizz.net,"November 12, 2002"

In [84]:
pd.read_csv(
    '../Data/tmdb.movies.csv.gz'
)

,Unnamed: 0,genre_ids,id,original_language,original_title,popularity,release_date,title,vote_average,vote_count
0,0,"[12, 14, 10751]",12444,en,Harry Potter and the Deathly Hallows: Part 1,33.533,2010-11-19,Harry Potter and the Deathly Hallows: Part 1,7.7,10788
1,1,"[14, 12, 16, 10751]",10191,en,How to Train Your Dragon,28.734,2010-03-26,How to Train Your Dragon,7.7,7610
2,2,"[12, 28, 878]",10138,en,Iron Man 2,28.515,2010-05-07,Iron Man 2,6.8,12368
3,3,"[16, 35, 10751]",862,en,Toy Story,28.005,1995-11-22,Toy Story,7.9,10174
4,4,"[28, 878, 12]",27205,en,Inception,27.920,2010-07-16,Inception,8.3,22186
...,...,...,...,...,...,...,...,...,...,...
26512,26512,"[27, 18]",488143,en,Laboratory Conditions,0.600,2018-10-13,Laboratory Conditions,0.0,1
26513,26513,"[18, 53]",485975,en,_EXHIBIT_84xxx_,0.600,2018-05-01,_EXHIBIT_84xxx_,0.0,1
26514,26514,"[14, 28, 12]",381231,en,The Last One,0.600,2018-10-01,The Last One,0.0,1
26515,26515,"[10751, 12, 28]",366854,en,Trailer Made,0.600,2018-06-22,Trailer Made,0.0,1
26516,26516,"[53, 27]",309885,en,The Church,0.600,2018-10-05,The Church,0.0,1